spring:
  application:
    name: task-service
  security:
    user:
      name: ${SERVICE_USERNAME:admin}
      password: ${SERVICE_PASS:pass}

server:
  port: 0
  servlet:
    context-path: /task-service

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_USERNAME:admin}:${SERVICE_PASS:pass}@localhost:8089/eureka


# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE

